apiVersion: v2
name: buildkit-controller
description: A Helm chart for BuildKit Kubernetes Operator
type: application
version: 0.0.2
appVersion: "0.0.2"
keywords:
  - buildkit
  - kubernetes
  - operator
  - ci/cd
home: https://github.com/smrt-devops/buildkit-controller
sources:
  - https://github.com/smrt-devops/buildkit-controller
maintainers:
  - name: BuildKit Team
icon: https://raw.githubusercontent.com/moby/buildkit/master/docs/buildkit-logo.png
