{{- if and .Values.controller.api.enabled .Values.controller.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "buildkit-controller.fullname" . }}-api-ingress
  namespace: {{ include "buildkit-controller.namespace" . }}
  labels:
    {{- include "buildkit-controller.labels" . | nindent 4 }}
    tailscale.com/proxy-class: acceptroutes
  {{- with .Values.controller.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.controller.api.ingress.ingressClassName }}
  ingressClassName: {{ .Values.controller.api.ingress.ingressClassName }}
  {{- end }}
  defaultBackend:
    service:
      name: {{ include "buildkit-controller.fullname" . }}-api
      port:
        number: {{ .Values.controller.api.port }}
  {{- if .Values.controller.api.ingress.tls.enabled }}
  tls:
    - hosts:
      - buildkit-controller-api
  {{- end }}
{{- end }}

